# AUTOGENERATED BY MAKE - DO NOT MODIFY MANUALLY
FROM resin/amd64-alpine

# Install ZIM (wikipedia etc) packages
ENV ZIMS    wiktionary_en_simple_all.zim
ENV ZIM_URL http://download.kiwix.org/zim

RUN mkdir -p /content/zim /content/kiwix /usr/src/kiwix \
 && apk add --update openssl \
 && KIWIX= \
 && BIN= \
 && if [ $(uname -m) = "x86_64" ]; then \
      KIWIX=kiwix-linux-x86_64 \
      ; BIN=kiwix/bin \
    ; else \
      KIWIX=kiwix-server-arm \
      ; BIN= \
      ; \
    fi \
 && wget -O - https://download.kiwix.org/bin/$KIWIX.tar.bz2 \
      | tar -C /usr/src/kiwix -xjf - \
 && mv /usr/src/kiwix/$BIN/* /usr/bin/ \
 && rm -rf /usr/src/kiwix \
 && for zim in $ZIMS; do \
      wget -O /content/zim/$zim $ZIM_URL/$zim \
      && ls /content/zim \
      && kiwix-index  /content/zim/$zim /content/kiwix/index \
      && kiwix-manage /content/kiwix/library.xml add /content/zim/$zim \
      ; \
    done


# Install httrack
RUN apk add --update -t build-deps build-base zlib-dev openssl-dev \
 && wget -O - https://github.com/xroche/httrack/archive/3.48.21.tar.gz \
      | tar -C /usr/src -xzf - \
 && cd /usr/src/httrack-3.48.21 \
 && ./configure \
 && make -j8 \
 && make install \
 && apk del build-deps \
 && rm -rf /usr/src/*

# Mirror Websites
ENV SITES http://elpissite.weebly.com
RUN mkdir -p /content/www \
 && cd /content/www \
 && httrack --ext-depth=1 $SITES \
 && find . -type f -maxdepth 1 -delete \
 && rm -rf hts-cache \
 && cd /content/www/elpissite.weebly.com \
 && for f in *.html; do sed -i 's/class=\"footer-wrap\".*/class=\"footer-wrap\" style=\"display:none;\" \/>/' $f; done \
 && for f in *.html; do sed -i 's/class=\"wsite-section-elements\".*/class=\"footer-wrap\" style=\"visibility:visible;\" \/>/' $f; done \
 && for f in *.html; do sed -i 's/scpt.parentNode.insertBefore(elem, scpt);//' $f; done \
 && for f in *.html; do sed -i 's/s.parentNode.insertBefore(ga, s);//' $f; done \
 && cd files \
 && for f in *.css; do sed -i 's/@import url(\x27http:\/\/fast.fonts.net\/t\/1.css?apiType=css&amp;projectid=b9a63dc3-765c-484e-bafe-ef372307f1b7?1485949767\x27);//' $f; done \
 && for f in *.css; do sed -i 's/http:\/\/elpissite.weebly.com\/files\/theme\/fonts/..\/elpissite.weebly.com\/files\/theme\/fonts/' $f; done \
 && cd ../../fonts.googleapis.com \
 && for f in *.css; do sed -i 's/http:\/\/fonts.gstatic.com/..\/fonts.gstatic.com/' $f; done 



RUN apk add --update hostapd dnsmasq s6 nginx openssh py-pip python \
 && sed -i 's/#PermitRootLogin.*/PermitRootLogin\ yes/' \
      /etc/ssh/sshd_config \
 && pip install ka-lite \
 && mkdir -p /data \
 && adduser -h /data/kalite kalite -D \
 && su -c 'kalite manage initialize_kalite' kalite

VOLUME [ "/data" ]

COPY files /

EXPOSE 80 8080 8008


ENTRYPOINT [ "/run.sh" ]
